--- # Web Server setup
- hosts: '{{ webhosts }}'
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    webhosts: webserver
    srcrepo: 'https://github.com/drewripa/cvwebpage.git'
    srcdest: '/var/www/html'
  tasks:
  - name: install HTTPD on webserver group
    yum:
      name: httpd
      state: latest
    notify:
    - startservice
  - name: install GIT on webserver group
    yum:
      name: git
      state: latest
  - name: clonerepo
    git:
      repo: '{{ srcrepo }}'
      dest: '{{ srcdest }}'
  handlers:
  - name: startservice
    service:
      name: httpd
      enabled: yes
      state: restarted
