--- #Web Server setup
- hosts: webserver
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: install HTTPD on webserver group
    yum:
      name: httpd
      state: latest
    notify:
    - startservice
  - name: install GIT on webserver group
    yum:
      name: git
      state: latest
  - name: clonerepo
    git:
      repo: 'https://github.com/drewripa/cvwebpage.git'
      dest: '/var/www/html'
  handlers:
  - name: startservice
    service:
      name: httpd
      enabled: yes
      state: restarted
